import JSZip from 'jszip';
import { kotlinCodeTemplates } from '../kotlinCodeTemplates';

/**
 * Generates a buildable and ready-to-import Jetpack Compose ZIP structure
 * for Android Studio.
 */
export const generateAndroidProjectZip = async (): Promise<Blob> => {
  const zip = new JSZip();

  // 1. Root Level configuration files
  zip.file(
    'settings.gradle.kts',
    `pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "StudentExpenseTracker"
include(":app")
`
  );

  zip.file(
    'build.gradle.kts',
    `// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id("com.android.application") version "8.2.2" apply false
    id("org.jetbrains.kotlin.android") version "1.9.22" apply false
}
`
  );

  zip.file(
    'gradle.properties',
    `org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
`
  );

  // 2. App Module
  const appFolder = zip.folder('app')!;

  // App Build.gradle (We can grab compiled build.gradle from our templates, or provide it here)
  const appGradleTemplate = kotlinCodeTemplates.find((t) => t.fileName === 'BuildGradle.kts')?.code || '';
  appFolder.file('build.gradle.kts', appGradleTemplate);

  // Manifest file
  const srcMainFolder = appFolder.folder('src/main')!;
  srcMainFolder.file(
    'AndroidManifest.xml',
    `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.student.tracker">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
        android:allowBackup="true"
        android:icon="@android:mipmap/sym_def_app_icon"
        android:label="Student Expense Tracker"
        android:roundIcon="@android:mipmap/sym_def_app_icon"
        android:supportsRtl="true"
        android:theme="@style/Theme.StudentExpenseTracker">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:theme="@style/Theme.StudentExpenseTracker">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`
  );

  // Resources
  const resValuesFolder = srcMainFolder.folder('res/values')!;
  resValuesFolder.file(
    'themes.xml',
    `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.StudentExpenseTracker" parent="android:Theme.Material.Light.NoActionBar" />
</resources>
`
  );

  // Java/Kotlin Sources
  const packageFolder = srcMainFolder.folder('java/com/student/tracker')!;
  
  // MainActivity.kt
  const mainActivityCode = kotlinCodeTemplates.find((t) => t.fileName === 'MainActivity.kt')?.code || '';
  packageFolder.file('MainActivity.kt', mainActivityCode);

  // Theme support folder
  const themeFolder = packageFolder.folder('ui/theme')!;
  const themeCode = kotlinCodeTemplates.find((t) => t.fileName === 'Theme.kt')?.code || '';
  themeFolder.file('Theme.kt', themeCode);
  
  themeFolder.file(
    'Type.kt',
    `package com.student.tracker.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

// Default Typography definitions for Material 3
val Typography = Typography(
    bodyLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = 16sp,
        lineHeight = 24sp,
        letterSpacing = 0.5sp
    )
)
`
  );

  // Generate local.properties standard mock
  zip.file(
    'local.properties',
    `# This file is automatically generated by Android Studio or during projects creation.
# Contain references to the location of Android SDK.
# Android Studio will automatically update this to point to your local Android SDK location.
`
  );

  // Return generated blob
  return await zip.generateAsync({ type: 'blob' });
};
